# compare: https://stackoverflow.com/a/67059629/

name: 'Submodule Notify Documentation Repo'

on:
  push:
    branches:
      - main    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Documentation Repo'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.DOCUMENTATION_TOKEN }}
        PARENT_REPO: brightway-lca/brightway-documentation
        PARENT_BRANCH: main
        WORKFLOW_ID: 43629004
      run: |
        curl \
          -fL --retry 3 -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ env.CI_TOKEN }}" \
          https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches \
          -d '{"ref":"${{ env.PARENT_BRANCH }}"}'